apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/kubeclaw-namespace.yaml
  - namespaces/kubeclaw-limitrange.yaml
  - namespaces/kubeclaw-resourcequota.yaml
  - rbac/kubeclaw-viewer-role.yaml
  - rbac/kubeclaw-viewer-binding.yaml
